spring:
  jwt:
    secret-key: 5c127c4d752bfa53cb742f13dc00f86efa1ad4323e17c6fe82e5dfbf0ad4ef9ac2f3282a374f5bcd3406e5bcaac84500ac71e2c75c548d325f5b393036fb4b21
  oauth:
    naver:
      secret: ggw1vW1qEh
      client-id: IjXEyMeqq6reHA7V6Qna
      url:
        auth: https://nid.naver.com
        api: https://openapi.naver.com
  datasource:
    url: jdbc:mysql://cleantest-db.czprjujkxgva.ap-northeast-2.rds.amazonaws.com:3306/cleanTest_DB?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: hyun
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL : debug
    org.hibernate.orm.jdbc.bind: trace
