spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: IjXEyMeqq6reHA7V6Qna
            client-secret: ggw1vW1qEh
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" # (== http://localhost:8080/login/oauth2/code/naver)
            authorization-grant-type: authorization_code
            scope: name, email, birthday, phoneNum
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
  datasource:
    url: jdbc:mysql://cleantest-db.czprjujkxgva.ap-northeast-2.rds.amazonaws.com:3306/cleanTest_DB?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: hyun
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL : debug
    org.hibernate.orm.jdbc.bind: trace
